-- Customer password reset (forgot-password flow). Run on existing SQL Server DBs.
IF OBJECT_ID(N'dbo.CUSTOMER_PASSWORD_RESET_TOKENS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CUSTOMER_PASSWORD_RESET_TOKENS
    (
        Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CUSTOMER_PASSWORD_RESET_TOKENS PRIMARY KEY,
        Email NVARCHAR(256) NOT NULL,
        TokenHash NVARCHAR(64) NOT NULL,
        ExpiresAt DATETIMEOFFSET(0) NOT NULL,
        UsedAt DATETIMEOFFSET(0) NULL,
        CreatedAt DATETIMEOFFSET(0) NOT NULL
            CONSTRAINT DF_CUSTOMER_PASSWORD_RESET_TOKENS_CreatedAt DEFAULT (SYSUTCDATETIME())
    );

    CREATE INDEX IX_CUSTOMER_PASSWORD_RESET_TOKENS_Email ON dbo.CUSTOMER_PASSWORD_RESET_TOKENS (Email);
    CREATE UNIQUE INDEX UX_CUSTOMER_PASSWORD_RESET_TOKENS_TokenHash ON dbo.CUSTOMER_PASSWORD_RESET_TOKENS (TokenHash);
END
GO
