/*
  Public-bank-style reporting tables (SQL Server).
  Column names follow the BDS layout; types are SQL Server–native equivalents.
  VALID_DTTM / PROCESSED_DTTM exist for layout parity but are left NULL by IH-QMS (system-generated in upstream feeds).

  Deploy alongside database/schema.sql on the same database when BDS mirroring is required.
  Enable runtime writes: appsettings "Bds:Enabled": true (see README).
*/

IF OBJECT_ID(N'dbo.BDS_QMS_TICKET', N'U') IS NULL
CREATE TABLE dbo.BDS_QMS_TICKET (
    TICKET_NUM      NVARCHAR(10)  NOT NULL,
    BRANCH_CD       INT             NOT NULL,
    STAFF_ID        NVARCHAR(10)  NOT NULL CONSTRAINT DF_BDS_TICKET_STAFF DEFAULT (N''),
    COUNTER_NUM     INT             NOT NULL CONSTRAINT DF_BDS_TICKET_COUNTER DEFAULT (0),
    TAKE_TIME       DATETIME2(3)    NOT NULL,
    WAITING_TIME    INT             NULL,
    ACS_PROFILE     NVARCHAR(20)  NOT NULL CONSTRAINT DF_BDS_TICKET_ACS DEFAULT (N'IHQMS'),
    CALL_TIME       DATETIME2(3)    NULL,
    WORKSTATION_NAME NVARCHAR(20) NOT NULL CONSTRAINT DF_BDS_TICKET_WS DEFAULT (N'IH-QMS'),
    SERVICE_NUM     NVARCHAR(20)  NOT NULL,
    VALID_DTTM      DATETIME2(3)    NULL,
    PROCESSED_DTTM  DATETIME2(3)    NULL,
    CONSTRAINT PK_BDS_QMS_TICKET PRIMARY KEY (BRANCH_CD, TICKET_NUM)
);

IF OBJECT_ID(N'dbo.BDS_QMS_AUDIT', N'U') IS NULL
CREATE TABLE dbo.BDS_QMS_AUDIT (
    AUDIT_ID        BIGINT          NOT NULL IDENTITY(1,1),
    TICKET_DATE     DATE            NOT NULL,
    BRANCH_CD       INT             NOT NULL,
    TICKET_NUM      NVARCHAR(10)  NOT NULL,
    ISSUED_TIME     DATETIME2(3)    NOT NULL,
    SERVED_TIME     DATETIME2(3)    NOT NULL,
    WAITING_TIME    INT             NOT NULL,
    COUNTER         INT             NOT NULL,
    SERVING_TIME    INT             NOT NULL,
    SERVICE         NVARCHAR(20)  NOT NULL,
    TELLER_ID       NVARCHAR(10)  NOT NULL,
    WORKSTATION_NAME NVARCHAR(20) NOT NULL,
    VALID_DTTM      DATETIME2(3)    NULL,
    PROCESSED_DTTM  DATETIME2(3)    NULL,
    CONSTRAINT PK_BDS_QMS_AUDIT PRIMARY KEY (AUDIT_ID)
);

IF OBJECT_ID(N'dbo.BDS_QMS_DAILY_TRANSACTION', N'U') IS NULL
CREATE TABLE dbo.BDS_QMS_DAILY_TRANSACTION (
    TRANSACTION_ID   BIGINT         NOT NULL IDENTITY(1,1),
    STAFF_ID         NVARCHAR(10) NOT NULL,
    BRANCH_CD        INT            NOT NULL,
    SEQUENCE_NUM     INT            NOT NULL,
    FUNCTION_CD      NVARCHAR(10) NOT NULL,
    HOST_TRAN_CD     NVARCHAR(10) NOT NULL,
    START_TIME       DATETIME2(3)   NOT NULL,
    END_TIME         DATETIME2(3)   NOT NULL,
    PROCESSING_TIME  INT            NOT NULL,
    SCREEN_NAME      NVARCHAR(200) NOT NULL,
    TICKET_NUM       NVARCHAR(10) NULL,
    ACS_PROFILE      NVARCHAR(20) NOT NULL,
    VALID_DTTM       DATETIME2(3)   NULL,
    PROCESSED_DTTM   DATETIME2(3)   NULL,
    CONSTRAINT PK_BDS_QMS_DAILY_TX PRIMARY KEY (TRANSACTION_ID)
);
