/*
  IH-QMS physical schema — aligned with QmsDbContext / EnsureCreated (net8 EF Core).
  Regenerate reference: dotnet ef dbcontext script --project src/QMS.Infrastructure --startup-project src/QMS.Api

  Optional BDS reporting (not in EF model): database/bds_public_layout.sql on the same database.
  Enable API mirror: appsettings "Bds": { "Enabled": true }.

  Greenfield: run once on empty dbo. Re-running is safe (IF NOT EXISTS / IF OBJECT_ID IS NULL).
  Prefer dotnet run (EnsureCreated) for dev; use this script when you need SSMS/sqlcmd DDL only.
*/

IF OBJECT_ID(N'dbo.BRANCHES', N'U') IS NULL
CREATE TABLE dbo.BRANCHES (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BRANCHES PRIMARY KEY,
    BranchCode INT NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Address NVARCHAR(400) NOT NULL,
    State NVARCHAR(80) NOT NULL,
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    OnlineQuotaPercent INT NOT NULL,
    SlotDurationMinutes INT NOT NULL,
    GeofenceMeters INT NOT NULL,
    ServiceZoneOffsetMinutes INT NOT NULL,
    OpeningStatus INT NOT NULL,
    OperatingHours NVARCHAR(200) NULL,
    ImageUrl NVARCHAR(800) NULL,
    MaxCapacity INT NULL,
    AdaptiveSlotCapacityEnabled BIT NOT NULL,
    MinSlotTotalCapacity INT NULL,
    OnlineEarlyCallMinutes INT NOT NULL,
    CalledAbsentGraceMinutes INT NOT NULL
);

IF OBJECT_ID(N'dbo.CUSTOMER_PASSWORD_RESET_TOKENS', N'U') IS NULL
CREATE TABLE dbo.CUSTOMER_PASSWORD_RESET_TOKENS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CUSTOMER_PASSWORD_RESET_TOKENS PRIMARY KEY,
    Email NVARCHAR(256) NOT NULL,
    TokenHash NVARCHAR(64) NOT NULL,
    ExpiresAt DATETIMEOFFSET NOT NULL,
    UsedAt DATETIMEOFFSET NULL,
    CreatedAt DATETIMEOFFSET NOT NULL CONSTRAINT DF_CUSTOMER_PASSWORD_RESET_TOKENS_CreatedAt DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00'))
);

IF OBJECT_ID(N'dbo.CUSTOMERS', N'U') IS NULL
CREATE TABLE dbo.CUSTOMERS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CUSTOMERS PRIMARY KEY,
    Email NVARCHAR(256) NOT NULL,
    Phone NVARCHAR(MAX) NULL,
    Name NVARCHAR(200) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    EmailVerified BIT NOT NULL,
    EmailVerificationToken NVARCHAR(128) NULL,
    EmailVerificationTokenExpiresAt DATETIMEOFFSET NULL,
    EmailOtpCode NVARCHAR(6) NULL,
    EmailOtpExpiresAt DATETIMEOFFSET NULL,
    EmailOtpAttempts INT NOT NULL,
    EmailOtpLastSentAt DATETIMEOFFSET NULL,
    PasswordResetOtpCode NVARCHAR(6) NULL,
    PasswordResetOtpExpiresAt DATETIMEOFFSET NULL,
    PasswordResetOtpAttempts INT NOT NULL,
    PasswordResetOtpLastSentAt DATETIMEOFFSET NULL,
    CreatedAt DATETIMEOFFSET NOT NULL CONSTRAINT DF_CUSTOMERS_CreatedAt DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00'))
);

IF OBJECT_ID(N'dbo.REFRESH_SESSIONS', N'U') IS NULL
CREATE TABLE dbo.REFRESH_SESSIONS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_REFRESH_SESSIONS PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash NVARCHAR(64) NOT NULL,
    ExpiresAt DATETIMEOFFSET NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    RevokedAt DATETIMEOFFSET NULL
);

IF OBJECT_ID(N'dbo.ANALYTICS_SUMMARY', N'U') IS NULL
CREATE TABLE dbo.ANALYTICS_SUMMARY (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ANALYTICS_SUMMARY PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ReportDate DATE NOT NULL,
    TotalCustomers INT NOT NULL,
    AvgWaitingMinutes FLOAT NULL,
    AvgServiceMinutes FLOAT NULL,
    NoShowRate FLOAT NULL,
    PeakHourLabel NVARCHAR(64) NULL,
    ComputedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT FK_ANALYTICS_SUMMARY_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.BRANCH_OPERATING_HOURS', N'U') IS NULL
CREATE TABLE dbo.BRANCH_OPERATING_HOURS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BRANCH_OPERATING_HOURS PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    DayOfWeek NVARCHAR(20) NOT NULL,
    OpenTime TIME NULL,
    CloseTime TIME NULL,
    IsClosed BIT NOT NULL,
    CONSTRAINT FK_BRANCH_OPERATING_HOURS_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.SERVICES', N'U') IS NULL
CREATE TABLE dbo.SERVICES (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SERVICES PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    Code NVARCHAR(32) NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    DefaultAvgServiceMinutes INT NOT NULL,
    PriorityWeight INT NOT NULL,
    CONSTRAINT FK_SERVICES_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.STAFF', N'U') IS NULL
CREATE TABLE dbo.STAFF (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_STAFF PRIMARY KEY,
    Email NVARCHAR(256) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Role INT NOT NULL,
    Status INT NOT NULL,
    CONSTRAINT FK_STAFF_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.CUSTOMER_FAVORITE_BRANCHES', N'U') IS NULL
CREATE TABLE dbo.CUSTOMER_FAVORITE_BRANCHES (
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_CUSTOMER_FAVORITE_BRANCHES PRIMARY KEY (CustomerId, BranchId),
    CONSTRAINT FK_CUSTOMER_FAVORITE_BRANCHES_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE,
    CONSTRAINT FK_CUSTOMER_FAVORITE_BRANCHES_CUSTOMERS_CustomerId FOREIGN KEY (CustomerId) REFERENCES dbo.CUSTOMERS(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.BOOKINGS', N'U') IS NULL
CREATE TABLE dbo.BOOKINGS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BOOKINGS PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    SlotStart DATETIMEOFFSET NOT NULL,
    SlotEnd DATETIMEOFFSET NOT NULL,
    Status INT NOT NULL,
    CheckedInAt DATETIMEOFFSET NULL,
    CONSTRAINT FK_BOOKINGS_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id),
    CONSTRAINT FK_BOOKINGS_CUSTOMERS_CustomerId FOREIGN KEY (CustomerId) REFERENCES dbo.CUSTOMERS(Id) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKINGS_SERVICES_ServiceTypeId FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id)
);

IF OBJECT_ID(N'dbo.ML_TRAINING_DATA', N'U') IS NULL
CREATE TABLE dbo.ML_TRAINING_DATA (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ML_TRAINING_DATA PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NULL,
    QueueLength INT NOT NULL,
    ActiveCounters INT NOT NULL,
    WaitingMinutes FLOAT NOT NULL,
    ServiceDurationMinutes FLOAT NOT NULL,
    HourOfDay INT NOT NULL,
    IsPeakHour BIT NOT NULL,
    SourceEventAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT FK_ML_TRAINING_DATA_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE,
    CONSTRAINT FK_ML_TRAINING_DATA_SERVICES_ServiceTypeId FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id)
);

IF OBJECT_ID(N'dbo.SERVICE_LOGS', N'U') IS NULL
CREATE TABLE dbo.SERVICE_LOGS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SERVICE_LOGS PRIMARY KEY,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    StaffId UNIQUEIDENTIFIER NULL,
    CounterId UNIQUEIDENTIFIER NULL,
    TicketNumber NVARCHAR(MAX) NOT NULL,
    StartedAt DATETIMEOFFSET NOT NULL,
    EndedAt DATETIMEOFFSET NOT NULL,
    DurationSeconds INT NOT NULL,
    CONSTRAINT FK_SERVICE_LOGS_SERVICES_ServiceTypeId FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.COUNTERS', N'U') IS NULL
CREATE TABLE dbo.COUNTERS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_COUNTERS PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    Number INT NOT NULL,
    Mode INT NOT NULL,
    StaffId UNIQUEIDENTIFIER NULL,
    CurrentServiceTypeId UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_COUNTERS_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE,
    CONSTRAINT FK_COUNTERS_SERVICES_CurrentServiceTypeId FOREIGN KEY (CurrentServiceTypeId) REFERENCES dbo.SERVICES(Id),
    CONSTRAINT FK_COUNTERS_STAFF_StaffId FOREIGN KEY (StaffId) REFERENCES dbo.STAFF(Id)
);

IF OBJECT_ID(N'dbo.NOTIFICATIONS', N'U') IS NULL
CREATE TABLE dbo.NOTIFICATIONS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_NOTIFICATIONS PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    BookingId UNIQUEIDENTIFIER NULL,
    Type INT NOT NULL,
    Message NVARCHAR(2000) NOT NULL,
    SentAt DATETIMEOFFSET NOT NULL,
    IsRead BIT NOT NULL,
    CONSTRAINT FK_NOTIFICATIONS_BOOKINGS_BookingId FOREIGN KEY (BookingId) REFERENCES dbo.BOOKINGS(Id),
    CONSTRAINT FK_NOTIFICATIONS_CUSTOMERS_CustomerId FOREIGN KEY (CustomerId) REFERENCES dbo.CUSTOMERS(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.COUNTER_ALLOWED_SERVICES', N'U') IS NULL
CREATE TABLE dbo.COUNTER_ALLOWED_SERVICES (
    CounterId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_COUNTER_ALLOWED_SERVICES PRIMARY KEY (CounterId, ServiceTypeId),
    CONSTRAINT FK_COUNTER_ALLOWED_SERVICES_COUNTERS_CounterId FOREIGN KEY (CounterId) REFERENCES dbo.COUNTERS(Id) ON DELETE CASCADE,
    CONSTRAINT FK_COUNTER_ALLOWED_SERVICES_SERVICES_ServiceTypeId FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id)
);

IF OBJECT_ID(N'dbo.QUEUE_TICKETS', N'U') IS NULL
CREATE TABLE dbo.QUEUE_TICKETS (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_QUEUE_TICKETS PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    TicketNumber NVARCHAR(32) NOT NULL,
    EntryType INT NOT NULL,
    State INT NOT NULL,
    BookingId UNIQUEIDENTIFIER NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    CalledAt DATETIMEOFFSET NULL,
    ServingStartedAt DATETIMEOFFSET NULL,
    ServingEndedAt DATETIMEOFFSET NULL,
    CounterId UNIQUEIDENTIFIER NULL,
    EnqueueSequence BIGINT NOT NULL,
    AssignedSlotStart DATETIMEOFFSET NULL,
    AssignedSlotEnd DATETIMEOFFSET NULL,
    CheckedIn BIT NOT NULL,
    CONSTRAINT FK_QUEUE_TICKETS_BOOKINGS_BookingId FOREIGN KEY (BookingId) REFERENCES dbo.BOOKINGS(Id) ON DELETE SET NULL,
    CONSTRAINT FK_QUEUE_TICKETS_BRANCHES_BranchId FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id),
    CONSTRAINT FK_QUEUE_TICKETS_COUNTERS_CounterId FOREIGN KEY (CounterId) REFERENCES dbo.COUNTERS(Id) ON DELETE SET NULL,
    CONSTRAINT FK_QUEUE_TICKETS_SERVICES_ServiceTypeId FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id)
);

/* Indexes — names match EF migrations script */

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ANALYTICS_SUMMARY_BranchId_ReportDate' AND object_id = OBJECT_ID(N'dbo.ANALYTICS_SUMMARY'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_ANALYTICS_SUMMARY_BranchId_ReportDate ON dbo.ANALYTICS_SUMMARY(BranchId, ReportDate);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_BOOKINGS_BranchId' AND object_id = OBJECT_ID(N'dbo.BOOKINGS'))
    CREATE NONCLUSTERED INDEX IX_BOOKINGS_BranchId ON dbo.BOOKINGS(BranchId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_BOOKINGS_CustomerId' AND object_id = OBJECT_ID(N'dbo.BOOKINGS'))
    CREATE NONCLUSTERED INDEX IX_BOOKINGS_CustomerId ON dbo.BOOKINGS(CustomerId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_BOOKINGS_ServiceTypeId' AND object_id = OBJECT_ID(N'dbo.BOOKINGS'))
    CREATE NONCLUSTERED INDEX IX_BOOKINGS_ServiceTypeId ON dbo.BOOKINGS(ServiceTypeId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_BRANCH_OPERATING_HOURS_BranchId_DayOfWeek' AND object_id = OBJECT_ID(N'dbo.BRANCH_OPERATING_HOURS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_BRANCH_OPERATING_HOURS_BranchId_DayOfWeek ON dbo.BRANCH_OPERATING_HOURS(BranchId, DayOfWeek);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_BRANCHES_BranchCode' AND object_id = OBJECT_ID(N'dbo.BRANCHES'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_BRANCHES_BranchCode ON dbo.BRANCHES(BranchCode);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_COUNTER_ALLOWED_SERVICES_ServiceTypeId' AND object_id = OBJECT_ID(N'dbo.COUNTER_ALLOWED_SERVICES'))
    CREATE NONCLUSTERED INDEX IX_COUNTER_ALLOWED_SERVICES_ServiceTypeId ON dbo.COUNTER_ALLOWED_SERVICES(ServiceTypeId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_COUNTERS_BranchId_Number' AND object_id = OBJECT_ID(N'dbo.COUNTERS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_COUNTERS_BranchId_Number ON dbo.COUNTERS(BranchId, Number);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_COUNTERS_CurrentServiceTypeId' AND object_id = OBJECT_ID(N'dbo.COUNTERS'))
    CREATE NONCLUSTERED INDEX IX_COUNTERS_CurrentServiceTypeId ON dbo.COUNTERS(CurrentServiceTypeId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_COUNTERS_StaffId' AND object_id = OBJECT_ID(N'dbo.COUNTERS'))
    CREATE NONCLUSTERED INDEX IX_COUNTERS_StaffId ON dbo.COUNTERS(StaffId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CUSTOMER_FAVORITE_BRANCHES_BranchId' AND object_id = OBJECT_ID(N'dbo.CUSTOMER_FAVORITE_BRANCHES'))
    CREATE NONCLUSTERED INDEX IX_CUSTOMER_FAVORITE_BRANCHES_BranchId ON dbo.CUSTOMER_FAVORITE_BRANCHES(BranchId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CUSTOMER_PASSWORD_RESET_TOKENS_TokenHash' AND object_id = OBJECT_ID(N'dbo.CUSTOMER_PASSWORD_RESET_TOKENS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_CUSTOMER_PASSWORD_RESET_TOKENS_TokenHash ON dbo.CUSTOMER_PASSWORD_RESET_TOKENS(TokenHash);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CUSTOMERS_Email' AND object_id = OBJECT_ID(N'dbo.CUSTOMERS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_CUSTOMERS_Email ON dbo.CUSTOMERS(Email);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CUSTOMERS_EmailVerificationToken' AND object_id = OBJECT_ID(N'dbo.CUSTOMERS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_CUSTOMERS_EmailVerificationToken ON dbo.CUSTOMERS(EmailVerificationToken) WHERE EmailVerificationToken IS NOT NULL;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ML_TRAINING_DATA_BranchId' AND object_id = OBJECT_ID(N'dbo.ML_TRAINING_DATA'))
    CREATE NONCLUSTERED INDEX IX_ML_TRAINING_DATA_BranchId ON dbo.ML_TRAINING_DATA(BranchId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ML_TRAINING_DATA_ServiceTypeId' AND object_id = OBJECT_ID(N'dbo.ML_TRAINING_DATA'))
    CREATE NONCLUSTERED INDEX IX_ML_TRAINING_DATA_ServiceTypeId ON dbo.ML_TRAINING_DATA(ServiceTypeId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_NOTIFICATIONS_BookingId' AND object_id = OBJECT_ID(N'dbo.NOTIFICATIONS'))
    CREATE NONCLUSTERED INDEX IX_NOTIFICATIONS_BookingId ON dbo.NOTIFICATIONS(BookingId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_NOTIFICATIONS_CustomerId' AND object_id = OBJECT_ID(N'dbo.NOTIFICATIONS'))
    CREATE NONCLUSTERED INDEX IX_NOTIFICATIONS_CustomerId ON dbo.NOTIFICATIONS(CustomerId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_QUEUE_TICKETS_BookingId' AND object_id = OBJECT_ID(N'dbo.QUEUE_TICKETS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_QUEUE_TICKETS_BookingId ON dbo.QUEUE_TICKETS(BookingId) WHERE BookingId IS NOT NULL;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_QUEUE_TICKETS_BranchId_TicketNumber' AND object_id = OBJECT_ID(N'dbo.QUEUE_TICKETS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_QUEUE_TICKETS_BranchId_TicketNumber ON dbo.QUEUE_TICKETS(BranchId, TicketNumber);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_QUEUE_TICKETS_CounterId' AND object_id = OBJECT_ID(N'dbo.QUEUE_TICKETS'))
    CREATE NONCLUSTERED INDEX IX_QUEUE_TICKETS_CounterId ON dbo.QUEUE_TICKETS(CounterId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_QUEUE_TICKETS_ServiceTypeId' AND object_id = OBJECT_ID(N'dbo.QUEUE_TICKETS'))
    CREATE NONCLUSTERED INDEX IX_QUEUE_TICKETS_ServiceTypeId ON dbo.QUEUE_TICKETS(ServiceTypeId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_REFRESH_SESSIONS_TokenHash' AND object_id = OBJECT_ID(N'dbo.REFRESH_SESSIONS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_REFRESH_SESSIONS_TokenHash ON dbo.REFRESH_SESSIONS(TokenHash);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_SERVICE_LOGS_ServiceTypeId' AND object_id = OBJECT_ID(N'dbo.SERVICE_LOGS'))
    CREATE NONCLUSTERED INDEX IX_SERVICE_LOGS_ServiceTypeId ON dbo.SERVICE_LOGS(ServiceTypeId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_SERVICES_BranchId_Code' AND object_id = OBJECT_ID(N'dbo.SERVICES'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_SERVICES_BranchId_Code ON dbo.SERVICES(BranchId, Code);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_STAFF_BranchId' AND object_id = OBJECT_ID(N'dbo.STAFF'))
    CREATE NONCLUSTERED INDEX IX_STAFF_BranchId ON dbo.STAFF(BranchId);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_STAFF_Email' AND object_id = OBJECT_ID(N'dbo.STAFF'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_STAFF_Email ON dbo.STAFF(Email);
