/*
  IH-QMS physical tables — names aligned with lecturer ERD / EF Core mappings (QmsDbContext ToTable).
  Bank-style reporting DDL (optional): database/bds_public_layout.sql — same database.
  When deployed, set appsettings "Bds": { "Enabled": true } so the API mirrors ticket lifecycle
  into BDS_QMS_TICKET / BDS_QMS_AUDIT (VALID_DTTM / PROCESSED_DTTM left NULL).

  If you have an older database (USERS, StaffUserId, …), migrate or recreate and run the API seeder.
*/

IF OBJECT_ID(N'dbo.BRANCHES', N'U') IS NULL
CREATE TABLE dbo.BRANCHES (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BranchCode INT NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Address NVARCHAR(400) NOT NULL CONSTRAINT DF_BRANCHES_Address DEFAULT (N''),
    State NVARCHAR(80) NOT NULL CONSTRAINT DF_BRANCHES_State DEFAULT (N''),
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    OnlineQuotaPercent INT NOT NULL,
    SlotDurationMinutes INT NOT NULL,
    GeofenceMeters INT NOT NULL,
    ServiceDayStartMinutes INT NOT NULL CONSTRAINT DF_BRANCHES_ServiceDayStart DEFAULT (540),
    ServiceDayEndMinutes INT NOT NULL CONSTRAINT DF_BRANCHES_ServiceDayEnd DEFAULT (1020),
    ServiceZoneOffsetMinutes INT NOT NULL CONSTRAINT DF_BRANCHES_ServiceZoneOffset DEFAULT (480),
    OpeningStatus INT NOT NULL CONSTRAINT DF_BRANCHES_OpeningStatus DEFAULT (0),
    OperatingHours NVARCHAR(200) NULL,
    MaxCapacity INT NULL,
    AdaptiveSlotCapacityEnabled BIT NOT NULL CONSTRAINT DF_BRANCHES_AdaptiveCapNew DEFAULT (1),
    MinSlotTotalCapacity INT NULL
);

IF OBJECT_ID(N'dbo.BRANCHES', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.BRANCHES', N'OpeningStatus') IS NULL
ALTER TABLE dbo.BRANCHES ADD OpeningStatus INT NOT NULL CONSTRAINT DF_BRANCHES_OpeningStatus2 DEFAULT (0);

IF OBJECT_ID(N'dbo.BRANCHES', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.BRANCHES', N'OperatingHours') IS NULL
ALTER TABLE dbo.BRANCHES ADD OperatingHours NVARCHAR(200) NULL;

IF OBJECT_ID(N'dbo.BRANCHES', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.BRANCHES', N'MaxCapacity') IS NULL
ALTER TABLE dbo.BRANCHES ADD MaxCapacity INT NULL;

IF OBJECT_ID(N'dbo.BRANCHES', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.BRANCHES', N'AdaptiveSlotCapacityEnabled') IS NULL
ALTER TABLE dbo.BRANCHES ADD AdaptiveSlotCapacityEnabled BIT NOT NULL CONSTRAINT DF_BRANCHES_AdaptiveCap DEFAULT (1);

IF OBJECT_ID(N'dbo.BRANCHES', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.BRANCHES', N'MinSlotTotalCapacity') IS NULL
ALTER TABLE dbo.BRANCHES ADD MinSlotTotalCapacity INT NULL;

IF OBJECT_ID(N'dbo.BRANCHES', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.BRANCHES', N'ImageUrl') IS NULL
ALTER TABLE dbo.BRANCHES ADD ImageUrl NVARCHAR(800) NULL;

IF OBJECT_ID(N'dbo.CUSTOMERS', N'U') IS NULL
CREATE TABLE dbo.CUSTOMERS (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Email NVARCHAR(256) NOT NULL,
    Phone NVARCHAR(32) NULL,
    Name NVARCHAR(200) NOT NULL,
    PasswordHash NVARCHAR(500) NOT NULL,
    PreferredBranchId UNIQUEIDENTIFIER NULL,
    CreatedAt DATETIMEOFFSET(7) NOT NULL CONSTRAINT DF_CUSTOMERS_CreatedAt DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT FK_CUSTOMERS_BRANCHES_Preferred FOREIGN KEY (PreferredBranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE SET NULL
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CUSTOMERS_Email' AND object_id = OBJECT_ID(N'dbo.CUSTOMERS'))
CREATE UNIQUE NONCLUSTERED INDEX IX_CUSTOMERS_Email ON dbo.CUSTOMERS(Email);

IF OBJECT_ID(N'dbo.SERVICES', N'U') IS NULL
CREATE TABLE dbo.SERVICES (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    Code NVARCHAR(32) NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    DefaultAvgServiceMinutes INT NOT NULL,
    PriorityWeight INT NOT NULL CONSTRAINT DF_SERVICES_PriorityWeight DEFAULT (1),
    CONSTRAINT FK_SERVICES_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.SERVICES', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.SERVICES', N'PriorityWeight') IS NULL
ALTER TABLE dbo.SERVICES ADD PriorityWeight INT NOT NULL CONSTRAINT DF_SERVICES_PriorityWeight2 DEFAULT (1);

IF OBJECT_ID(N'dbo.STAFF', N'U') IS NULL
CREATE TABLE dbo.STAFF (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Email NVARCHAR(256) NOT NULL,
    PasswordHash NVARCHAR(500) NOT NULL,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Role INT NOT NULL,
    Status INT NOT NULL,
    CONSTRAINT FK_STAFF_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_STAFF_Email' AND object_id = OBJECT_ID(N'dbo.STAFF'))
CREATE UNIQUE NONCLUSTERED INDEX IX_STAFF_Email ON dbo.STAFF(Email);

IF OBJECT_ID(N'dbo.COUNTERS', N'U') IS NULL
CREATE TABLE dbo.COUNTERS (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    Number INT NOT NULL,
    Mode INT NOT NULL,
    StaffId UNIQUEIDENTIFIER NULL,
    CurrentServiceTypeId UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_COUNTERS_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE,
    CONSTRAINT FK_COUNTERS_STAFF FOREIGN KEY (StaffId) REFERENCES dbo.STAFF(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_COUNTERS_SERVICES_Current FOREIGN KEY (CurrentServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE NO ACTION
);

IF OBJECT_ID(N'dbo.COUNTERS', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.COUNTERS', N'CurrentServiceTypeId') IS NULL
ALTER TABLE dbo.COUNTERS ADD CurrentServiceTypeId UNIQUEIDENTIFIER NULL
    CONSTRAINT FK_COUNTERS_SERVICES_Current2 FOREIGN KEY (CurrentServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE NO ACTION;

IF OBJECT_ID(N'dbo.COUNTER_ALLOWED_SERVICES', N'U') IS NULL
CREATE TABLE dbo.COUNTER_ALLOWED_SERVICES (
    CounterId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_COUNTER_ALLOWED_SERVICES PRIMARY KEY (CounterId, ServiceTypeId),
    CONSTRAINT FK_COUNTER_ALLOWED_COUNTERS FOREIGN KEY (CounterId) REFERENCES dbo.COUNTERS(Id) ON DELETE CASCADE,
    CONSTRAINT FK_COUNTER_ALLOWED_SERVICES FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE NO ACTION
);

IF OBJECT_ID(N'dbo.TIME_SLOTS', N'U') IS NULL
CREATE TABLE dbo.TIME_SLOTS (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    StartTime DATETIMEOFFSET(7) NOT NULL,
    EndTime DATETIMEOFFSET(7) NOT NULL,
    TotalCapacity INT NOT NULL,
    OnlineQuota INT NOT NULL,
    WalkInQuota INT NOT NULL,
    BookedOnline INT NOT NULL CONSTRAINT DF_TIME_SLOTS_BookedOnline DEFAULT (0),
    BookedWalkin INT NOT NULL CONSTRAINT DF_TIME_SLOTS_BookedWalkin DEFAULT (0),
    Status INT NOT NULL CONSTRAINT DF_TIME_SLOTS_Status DEFAULT (0),
    CONSTRAINT FK_TIME_SLOTS_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE,
    CONSTRAINT FK_TIME_SLOTS_SERVICES FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE NO ACTION
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_TIME_SLOTS_Branch_Service_Start_End' AND object_id = OBJECT_ID(N'dbo.TIME_SLOTS'))
CREATE NONCLUSTERED INDEX IX_TIME_SLOTS_Branch_Service_Start_End
    ON dbo.TIME_SLOTS (BranchId, ServiceTypeId, StartTime, EndTime);

IF OBJECT_ID(N'dbo.BOOKINGS', N'U') IS NULL
CREATE TABLE dbo.BOOKINGS (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    TimeSlotId UNIQUEIDENTIFIER NULL,
    SlotStart DATETIMEOFFSET(7) NOT NULL,
    SlotEnd DATETIMEOFFSET(7) NOT NULL,
    Status INT NOT NULL,
    CheckedInAt DATETIMEOFFSET(7) NULL,
    CONSTRAINT FK_BOOKINGS_CUSTOMERS FOREIGN KEY (CustomerId) REFERENCES dbo.CUSTOMERS(Id) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKINGS_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_BOOKINGS_SERVICES FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_BOOKINGS_TIME_SLOTS FOREIGN KEY (TimeSlotId) REFERENCES dbo.TIME_SLOTS(Id) ON DELETE SET NULL
);

IF OBJECT_ID(N'dbo.BOOKINGS', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.BOOKINGS', N'TimeSlotId') IS NULL
ALTER TABLE dbo.BOOKINGS ADD TimeSlotId UNIQUEIDENTIFIER NULL
    CONSTRAINT FK_BOOKINGS_TIME_SLOTS2 FOREIGN KEY (TimeSlotId) REFERENCES dbo.TIME_SLOTS(Id) ON DELETE SET NULL;

IF OBJECT_ID(N'dbo.QUEUE_TICKETS', N'U') IS NULL
CREATE TABLE dbo.QUEUE_TICKETS (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    TicketNumber NVARCHAR(32) NOT NULL,
    EntryType INT NOT NULL,
    State INT NOT NULL,
    BookingId UNIQUEIDENTIFIER NULL,
    CreatedAt DATETIMEOFFSET(7) NOT NULL,
    CalledAt DATETIMEOFFSET(7) NULL,
    ServingStartedAt DATETIMEOFFSET(7) NULL,
    ServingEndedAt DATETIMEOFFSET(7) NULL,
    CounterId UNIQUEIDENTIFIER NULL,
    EnqueueSequence BIGINT NOT NULL,
    WalkInCapacityBucketStart DATETIMEOFFSET(7) NULL,
    WalkInCapacityBucketEnd DATETIMEOFFSET(7) NULL,
    CONSTRAINT FK_QUEUE_TICKETS_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_QUEUE_TICKETS_SERVICES FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_QUEUE_TICKETS_COUNTERS FOREIGN KEY (CounterId) REFERENCES dbo.COUNTERS(Id) ON DELETE SET NULL,
    CONSTRAINT FK_QUEUE_TICKETS_BOOKINGS FOREIGN KEY (BookingId) REFERENCES dbo.BOOKINGS(Id) ON DELETE SET NULL
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_QUEUE_TICKETS_BookingId' AND object_id = OBJECT_ID(N'dbo.QUEUE_TICKETS'))
CREATE UNIQUE NONCLUSTERED INDEX IX_QUEUE_TICKETS_BookingId ON dbo.QUEUE_TICKETS(BookingId) WHERE BookingId IS NOT NULL;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_QUEUE_TICKETS_Branch_Ticket' AND object_id = OBJECT_ID(N'dbo.QUEUE_TICKETS'))
CREATE UNIQUE NONCLUSTERED INDEX IX_QUEUE_TICKETS_Branch_Ticket ON dbo.QUEUE_TICKETS(BranchId, TicketNumber);

IF OBJECT_ID(N'dbo.SERVICE_LOGS', N'U') IS NULL
CREATE TABLE dbo.SERVICE_LOGS (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ServiceTypeId UNIQUEIDENTIFIER NOT NULL,
    StaffId UNIQUEIDENTIFIER NULL,
    CounterId UNIQUEIDENTIFIER NULL,
    TicketNumber NVARCHAR(16) NOT NULL,
    StartedAt DATETIMEOFFSET(7) NOT NULL,
    EndedAt DATETIMEOFFSET(7) NOT NULL,
    DurationSeconds INT NOT NULL,
    CONSTRAINT FK_SERVICE_LOGS_SERVICES FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.NOTIFICATIONS', N'U') IS NULL
CREATE TABLE dbo.NOTIFICATIONS (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    BookingId UNIQUEIDENTIFIER NULL,
    Type INT NOT NULL,
    Message NVARCHAR(2000) NOT NULL,
    SentAt DATETIMEOFFSET(7) NOT NULL,
    IsRead BIT NOT NULL CONSTRAINT DF_NOTIFICATIONS_IsRead DEFAULT (0),
    CONSTRAINT FK_NOTIFICATIONS_CUSTOMERS FOREIGN KEY (CustomerId) REFERENCES dbo.CUSTOMERS(Id) ON DELETE CASCADE,
    CONSTRAINT FK_NOTIFICATIONS_BOOKINGS FOREIGN KEY (BookingId) REFERENCES dbo.BOOKINGS(Id) ON DELETE SET NULL
);

IF OBJECT_ID(N'dbo.ANALYTICS_SUMMARY', N'U') IS NULL
CREATE TABLE dbo.ANALYTICS_SUMMARY (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ReportDate DATE NOT NULL,
    TotalCustomers INT NOT NULL CONSTRAINT DF_ANALYTICS_SUMMARY_Total DEFAULT (0),
    AvgWaitingMinutes FLOAT NULL,
    AvgServiceMinutes FLOAT NULL,
    NoShowRate FLOAT NULL,
    PeakHourLabel NVARCHAR(64) NULL,
    ComputedAt DATETIMEOFFSET(7) NOT NULL,
    CONSTRAINT UQ_ANALYTICS_SUMMARY_Branch_Date UNIQUE (BranchId, ReportDate),
    CONSTRAINT FK_ANALYTICS_SUMMARY_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE
);

IF OBJECT_ID(N'dbo.ML_TRAINING_DATA', N'U') IS NULL
CREATE TABLE dbo.ML_TRAINING_DATA (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    ServiceTypeId UNIQUEIDENTIFIER NULL,
    QueueLength INT NOT NULL,
    ActiveCounters INT NOT NULL,
    WaitingMinutes FLOAT NOT NULL,
    ServiceDurationMinutes FLOAT NOT NULL,
    HourOfDay INT NOT NULL,
    IsPeakHour BIT NOT NULL CONSTRAINT DF_ML_TRAINING_DATA_Peak DEFAULT (0),
    SourceEventAt DATETIMEOFFSET(7) NOT NULL,
    CONSTRAINT FK_ML_TRAINING_DATA_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE,
    CONSTRAINT FK_ML_TRAINING_DATA_SERVICES FOREIGN KEY (ServiceTypeId) REFERENCES dbo.SERVICES(Id) ON DELETE NO ACTION
);
