-- 档 B Phase 1: SERVICE_QUEUES + QueueId + daily ticket reuse
IF OBJECT_ID(N'dbo.SERVICE_QUEUES', N'U') IS NULL
CREATE TABLE dbo.SERVICE_QUEUES (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SERVICE_QUEUES PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    TicketPrefix NVARCHAR(8) NOT NULL,
    ServiceLevelMinutes INT NOT NULL CONSTRAINT DF_SERVICE_QUEUES_SLA DEFAULT 15,
    IsActive BIT NOT NULL CONSTRAINT DF_SERVICE_QUEUES_Active DEFAULT 1,
    CreatedAt DATETIMEOFFSET NOT NULL CONSTRAINT DF_SERVICE_QUEUES_CreatedAt DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT FK_SERVICE_QUEUES_BRANCHES FOREIGN KEY (BranchId) REFERENCES dbo.BRANCHES(Id) ON DELETE CASCADE
);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_SERVICE_QUEUES_BranchId_TicketPrefix' AND object_id = OBJECT_ID(N'dbo.SERVICE_QUEUES'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_SERVICE_QUEUES_BranchId_TicketPrefix ON dbo.SERVICE_QUEUES(BranchId, TicketPrefix);

IF COL_LENGTH(N'dbo.SERVICES', N'QueueId') IS NULL
    ALTER TABLE dbo.SERVICES ADD QueueId UNIQUEIDENTIFIER NULL;
IF COL_LENGTH(N'dbo.QUEUE_TICKETS', N'QueueId') IS NULL
    ALTER TABLE dbo.QUEUE_TICKETS ADD QueueId UNIQUEIDENTIFIER NULL;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_QUEUE_TICKETS_BranchId_TicketNumber' AND object_id = OBJECT_ID(N'dbo.QUEUE_TICKETS'))
    DROP INDEX IX_QUEUE_TICKETS_BranchId_TicketNumber ON dbo.QUEUE_TICKETS;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_QUEUE_TICKETS_BranchId_TicketNumber_Open' AND object_id = OBJECT_ID(N'dbo.QUEUE_TICKETS'))
    CREATE UNIQUE NONCLUSTERED INDEX IX_QUEUE_TICKETS_BranchId_TicketNumber_Open
    ON dbo.QUEUE_TICKETS(BranchId, TicketNumber) WHERE [State] IN (0, 1, 2);

-- Optional seed: one queue per service (API ServiceQueueProvisioning also does this on startup)
